# Remote write configuration for Influx
remote_write:
  - url: "http://10.104.0.2:8086/api/v1/prom/write?db=prometheus_db&u=admin&p=password"
scrape_configs:
  - job_name: 'amari_exporter'
    scrape_interval: 1s
    static_configs:
      - targets: ["localhost:3333"]
  - job_name: 'node_exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9100"]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'node_cpu_seconds_total|node_memory_Buffers_bytes|node_memory_Cached_bytes|node_memory_Mem.+|node_memory_Swap.+|node_network_receive_bytes_total|node_network_transmit_bytes_total|node_filesyste$
        action: keep

