{
 "title": "MonB5G",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Monitoring Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Monitoring data and model exchange data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "Cumulative Raw monitoring data size",
     "measurement": "general",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " * 4 * 8 / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "general" }
     ]
    },
    {
     "alias": "Comulative model size data exchange",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "model_size",
     "select": [
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " * 8 / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "BS1" }
     ]
    }
   ]
  },
  {
   "title": "Generated Slice Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "DL Traffic slice 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traffic",
     "select": [
      [
       { "params": [ "Download Speed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "traffic_gen_ID", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "DL Traffic slice 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traffic",
     "select": [
      [
       { "params": [ "Download Speed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "traffic_gen_ID", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "DL Traffic slice 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traffic",
     "select": [
      [
       { "params": [ "Download Speed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "traffic_gen_ID", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "DL Traffic slice 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traffic",
     "select": [
      [
       { "params": [ "Download Speed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "traffic_gen_ID", "operator": "=", "value": "4" }
     ]
    }
   ]
  },
  {
   "title": "Reward",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "Reward Slice 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reward",
     "select": [
      [
       { "params": [ "r" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "slice_0" }
     ]
    },
    {
     "alias": "Reward Slice 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reward",
     "select": [
      [
       { "params": [ "r" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "slice_1" }
     ]
    },
    {
     "alias": "Reward Slice 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "reward",
     "select": [
      [
       { "params": [ "r" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "slice_2" }
     ]
    }
   ]
  },
  {
   "title": "DL Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "alias": "Slice 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cell",
     "select": [
      [
       { "params": [ "cell_dl_bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "  / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "cell_id_1" }
     ]
    },
    {
     "alias": "Slice 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cell",
     "select": [
      [
       { "params": [ "cell_dl_bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "  / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "cell_id_2" }
     ]
    },
    {
     "alias": "Slice 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cell",
     "select": [
      [
       { "params": [ "cell_dl_bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "  / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "cell_id_3" }
     ]
    },
    {
     "alias": "Slice 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cell",
     "select": [
      [
       { "params": [ "cell_dl_bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "  / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "cell_id_4" }
     ]
    }
   ]
  },
  {
   "title": "PRB allocation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DL PRB Slice 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prb_allocation",
     "select": [
      [
       { "params": [ "dl_prb" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "slice_0" }
     ]
    },
    {
     "alias": "DL PRB Slice 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prb_allocation",
     "select": [
      [
       { "params": [ "dl_prb" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "slice_1" }
     ]
    },
    {
     "alias": "DL PRB Slice 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prb_allocation",
     "select": [
      [
       { "params": [ "dl_prb" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "slice_2" }
     ]
    }
   ]
  },
  {
   "title": "PRB allocation eNB1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "alias": "DL PRB Slice 1 eNB 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prb_allocation",
     "select": [
      [
       { "params": [ "dl_prb" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "slice_0" },
      { "condition": "AND", "key": "veNB", "operator": "=", "value": "VBS1" }
     ]
    },
    {
     "alias": "DL PRB Slice 2 eNB 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prb_allocation",
     "select": [
      [
       { "params": [ "dl_prb" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "slice_1" },
      { "condition": "AND", "key": "veNB", "operator": "=", "value": "VBS1" }
     ]
    }
   ]
  },
  {
   "title": "PRB allocation eNB 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "alias": "DL PRB Slice 1 eNB 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prb_allocation",
     "select": [
      [
       { "params": [ "dl_prb" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "slice_0" },
      { "condition": "AND", "key": "veNB", "operator": "=", "value": "VBS2" }
     ]
    },
    {
     "alias": "DL PRB Slice 2 eNB 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prb_allocation",
     "select": [
      [
       { "params": [ "dl_prb" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "slice_1" },
      { "condition": "AND", "key": "veNB", "operator": "=", "value": "VBS2" }
     ]
    }
   ]
  },
  {
   "title": "Federation Epoch",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "model_size",
     "select": [
      [
       { "params": [ "fed_epoch" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RCC_Connected UEs",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Slice 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cell",
     "select": [
      [
       { "params": [ "cell_dl_sched_users_max" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "cell_id_1" }
     ]
    },
    {
     "alias": "Slice 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "cell",
     "select": [
      [
       { "params": [ "cell_dl_sched_users_max" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "cell_id_2" }
     ]
    },
    {
     "alias": "Slice 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "cell",
     "select": [
      [
       { "params": [ "cell_dl_sched_users_max" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "cell_id_3" }
     ]
    }
   ]
  },
  {
   "title": "Allocation Gap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "alias": "Allocation Gap Slice 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prb_allocation",
     "select": [
      [
       { "params": [ "dl_gap" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "slice_0" }
     ]
    },
    {
     "alias": "Allocation Gap Slice 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prb_allocation",
     "select": [
      [
       { "params": [ "dl_gap" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "  / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "slice_1" }
     ]
    },
    {
     "alias": "Allocation Gap Slice 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prb_allocation",
     "select": [
      [
       { "params": [ "dl_gap" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "slice_2" }
     ]
    }
   ]
  },
  {
   "title": "MCS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DL MCS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ues",
     "select": [
      [
       { "params": [ "dl_mcs" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "UL MCS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ues",
     "select": [
      [
       { "params": [ "ul_mcs" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 33 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "general",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Auxiliary information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "UL Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "alias": "Slice 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cell",
     "select": [
      [
       { "params": [ "cell_ul_bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "cell_id_1" }
     ]
    },
    {
     "alias": "Slice 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cell",
     "select": [
      [
       { "params": [ "cell_ul_bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "cell_id_2" }
     ]
    },
    {
     "alias": "Slice 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cell",
     "select": [
      [
       { "params": [ "cell_ul_bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "cell_id_3" }
     ]
    }
   ]
  },
  {
   "title": "Avg Delay RF Ports",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "alias": "Slice 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rf_port",
     "select": [
      [
       { "params": [ "rxtx_delay_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "rf_port_id_0" }
     ]
    },
    {
     "alias": "Slice 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rf_port",
     "select": [
      [
       { "params": [ "rxtx_delay_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "rf_port_id_1" }
     ]
    },
    {
     "alias": "Slice 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rf_port",
     "select": [
      [
       { "params": [ "rxtx_delay_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "rf_port_id_2" }
     ]
    }
   ]
  },
  {
   "title": "UE Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "alias": "DL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ues",
     "select": [
      [
       { "params": [ "dl_bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "UL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ues",
     "select": [
      [
       { "params": [ "ul_bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GTP Total DL bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "general",
     "select": [
      [
       { "params": [ "gtp_rx_bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}